# -*- coding: utf-8 -*-
"""4_mar_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQZPs1jUM8sJ6RQdqvxFyT5zRX8eImzZ
"""

# Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a scatter plot for age and fare columns in the titanic dataset.

import seaborn as sb

titanic = sb.load_dataset('titanic')

titanic

import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=titanic.age , y=titanic.fare , mode='markers' ))
fig.show()

# Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express.
# Ans.

import plotly.express as px
 
df = px.data.tips()
 
fig = px.box(df, x = "sex", y="total_bill")
fig.show()

# Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
#     the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
#     column with the color parameter.

# Ans.

import plotly.express as px
  
df = px.data.tips()
  
fig = px.histogram(df, x="sex",y="total_bill" ,pattern_shape="smoker", color = "day")
fig.show()

# Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for the color parameter.

# Ans.

import plotly.express as px
  
df = px.data.iris()
fig = px.scatter_matrix(df,dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],color="species")
fig.show()

# Q5. What is Distplot? Using Plotly express, plot a distplot.
# Ans. The distplot represents the univariate distribution of data i.e. data distribution of a variable against the density distribution.

import plotly.figure_factory as ff
import numpy as np
np.random.seed(1)

x = np.random.randn(1000)
hist_data = [x]
group_labels = ['distplot']

fig = ff.create_distplot(hist_data, group_labels)
fig.show()

